version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo Installing Composer...
      - composer install --no-dev --optimize-autoloader
  pre_build:
    commands:
      - echo Pre-build steps...
      - cp .env.example .env
      - php artisan key:generate
  build:
    commands:
      - echo Optimizing Laravel...
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
    - "!node_modules/**"
    - "!tests/**"
    - "!storage/logs/**"
  discard-paths: no
